// apps/nativescript-starter-svelte/app/components/Home.svelte
<page>
    <actionBar title="Home" />
    <gridLayout>
        <label class="info" text="{message}" />
    </gridLayout>
</page>

<script lang="ts">
    let message: string = "Blank Svelte Native App"
</script>

<style>
    .info {
        font-size: 20;
        horizontal-align: center;
        vertical-align: center;
    }
</style>

// apps/nativescript-starter-vue/app/components/Home.vue
<template>
  <Page>
    <ActionBar>
      <Label text="Home"/>
    </ActionBar>

    <GridLayout>
      <Label class="info" :text="message" @tap="logMessage" />
    </GridLayout>
  </Page>
</template>

<script lang="ts">
  import Vue from "nativescript-vue";

  export default Vue.extend({
    computed: {
      message() {
        return "Blank {N}-Vue app";
      }
    },

    methods: {
      logMessage() {
        console.log('You have tapped the message!')
      }
    }
  });
</script>

<style scoped>
  .info {
    font-size: 20;
    horizontal-align: center;
    vertical-align: center;
  }
</style>
